// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9kr9XD1_J9G6Ilz5PKA0x3zs4a9887LY',
    appId: '1:583795890900:web:aa36c4bf075eea71233941',
    messagingSenderId: '583795890900',
    projectId: 'wound-care-app2',
    authDomain: 'wound-care-app2.firebaseapp.com',
    storageBucket: 'wound-care-app2.firebasestorage.app',
    measurementId: 'G-GLTQVM76R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOHVJwxli1vUzBVAVA14pCUVphzpuesBw',
    appId: '1:583795890900:android:d9a64a4b71dc0130233941',
    messagingSenderId: '583795890900',
    projectId: 'wound-care-app2',
    storageBucket: 'wound-care-app2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOw_CqGNM1ai0mA_ZLDTkmL5AKebh5VhY',
    appId: '1:583795890900:ios:48fc5af887229945233941',
    messagingSenderId: '583795890900',
    projectId: 'wound-care-app2',
    storageBucket: 'wound-care-app2.firebasestorage.app',
    iosBundleId: 'com.example.woundCareApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOw_CqGNM1ai0mA_ZLDTkmL5AKebh5VhY',
    appId: '1:583795890900:ios:48fc5af887229945233941',
    messagingSenderId: '583795890900',
    projectId: 'wound-care-app2',
    storageBucket: 'wound-care-app2.firebasestorage.app',
    iosBundleId: 'com.example.woundCareApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9kr9XD1_J9G6Ilz5PKA0x3zs4a9887LY',
    appId: '1:583795890900:web:ecd0444e470c0dff233941',
    messagingSenderId: '583795890900',
    projectId: 'wound-care-app2',
    authDomain: 'wound-care-app2.firebaseapp.com',
    storageBucket: 'wound-care-app2.firebasestorage.app',
    measurementId: 'G-DFH7XQF9EQ',
  );
}
